[tools]
adr-tools = "latest"
go = "latest"
golangci-lint = "latest"
"go:golang.org/x/tools/gopls" = "latest"
helm = "latest"
k6 = "latest"
k9s = "latest"
kind = "latest"
kubebuilder = "latest"
kubectl = "latest"
kubelogin = "latest"
node = "22.22.0"
usage = "latest"
watchexec = "latest"
yarn = "4.12.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
